version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: supgeuk_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supgeuk_war
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: supgeuk_redis
    ports:
      - "6380:6379"
    restart: unless-stopped

volumes:
  postgres_data_v2:
