""" Initial migration

Revision ID: 135fafa0ddcf
Revises: 
Create Date: 2026-05-08 15:07:28.428701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135fafa0ddcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_pattern_stats',
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('avg_return_5d', sa.Float(), nullable=True),
    sa.Column('win_rate_5d', sa.Float(), nullable=True),
    sa.Column('avg_return_20d', sa.Float(), nullable=True),
    sa.Column('win_rate_20d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('type', 'as_of_date')
    )
    op.create_table('ma_events',
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('short_value', sa.Float(), nullable=False),
    sa.Column('long_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date', 'event_type')
    )
    op.create_index('ix_ma_events_ticker_date', 'ma_events', ['ticker', 'date'], unique=False)
    op.create_table('market_index',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kospi_close', sa.Float(), nullable=True),
    sa.Column('kospi_change_pct', sa.Float(), nullable=True),
    sa.Column('kosdaq_close', sa.Float(), nullable=True),
    sa.Column('kosdaq_change_pct', sa.Float(), nullable=True),
    sa.Column('usdkrw_close', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('market_indicators',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('ma_5', sa.Float(), nullable=True),
    sa.Column('ma_20', sa.Float(), nullable=True),
    sa.Column('ma_60', sa.Float(), nullable=True),
    sa.Column('ma_120', sa.Float(), nullable=True),
    sa.Column('dominance_indi', sa.Float(), nullable=True),
    sa.Column('dominance_inst', sa.Float(), nullable=True),
    sa.Column('dominance_frgn', sa.Float(), nullable=True),
    sa.Column('sfi_inst', sa.Float(), nullable=True),
    sa.Column('sfi_frgn', sa.Float(), nullable=True),
    sa.Column('quadrant', sa.String(length=32), nullable=True),
    sa.Column('conflict_intensity', sa.Float(), nullable=True),
    sa.Column('avg_cost_5d_inst', sa.Float(), nullable=True),
    sa.Column('avg_cost_20d_inst', sa.Float(), nullable=True),
    sa.Column('avg_cost_60d_inst', sa.Float(), nullable=True),
    sa.Column('avg_cost_5d_frgn', sa.Float(), nullable=True),
    sa.Column('avg_cost_20d_frgn', sa.Float(), nullable=True),
    sa.Column('avg_cost_60d_frgn', sa.Float(), nullable=True),
    sa.Column('defense_status', sa.String(length=32), nullable=True),
    sa.Column('defense_status_inverted', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('type_intensity', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('weighted_priority', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'ticker')
    )
    op.create_index('ix_market_indicators_date_defense_status', 'market_indicators', ['date', 'defense_status'], unique=False)
    op.create_index('ix_market_indicators_date_type', 'market_indicators', ['date', 'type'], unique=False)
    op.create_index('ix_market_indicators_date_weighted_priority', 'market_indicators', ['date', 'weighted_priority'], unique=False)
    op.create_table('market_raw_data',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('open', sa.Integer(), nullable=True),
    sa.Column('high', sa.Integer(), nullable=True),
    sa.Column('low', sa.Integer(), nullable=True),
    sa.Column('close', sa.Integer(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('trade_value', sa.BigInteger(), nullable=True),
    sa.Column('net_buy_indi', sa.BigInteger(), nullable=True),
    sa.Column('net_buy_inst', sa.BigInteger(), nullable=True),
    sa.Column('net_buy_frgn', sa.BigInteger(), nullable=True),
    sa.Column('net_qty_inst', sa.BigInteger(), nullable=True),
    sa.Column('net_qty_frgn', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'ticker')
    )
    op.create_index('ix_market_raw_data_ticker_date', 'market_raw_data', ['ticker', 'date'], unique=False)
    op.create_table('market_summary',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market_sfi_inst_kospi', sa.Float(), nullable=True),
    sa.Column('market_sfi_inst_kosdaq', sa.Float(), nullable=True),
    sa.Column('market_sfi_inst_total', sa.Float(), nullable=True),
    sa.Column('market_sfi_frgn_kospi', sa.Float(), nullable=True),
    sa.Column('market_sfi_frgn_kosdaq', sa.Float(), nullable=True),
    sa.Column('market_sfi_frgn_total', sa.Float(), nullable=True),
    sa.Column('top_sector_inst', sa.String(length=64), nullable=True),
    sa.Column('top_sector_frgn', sa.String(length=64), nullable=True),
    sa.Column('count_type_a', sa.Integer(), nullable=True),
    sa.Column('count_type_b', sa.Integer(), nullable=True),
    sa.Column('count_type_c', sa.Integer(), nullable=True),
    sa.Column('count_type_d', sa.Integer(), nullable=True),
    sa.Column('market_brief_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('stock_master',
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index('ix_stock_master_market', 'stock_master', ['market'], unique=False)
    op.create_index('ix_stock_master_sector', 'stock_master', ['sector'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_master_sector', table_name='stock_master')
    op.drop_index('ix_stock_master_market', table_name='stock_master')
    op.drop_table('stock_master')
    op.drop_table('market_summary')
    op.drop_index('ix_market_raw_data_ticker_date', table_name='market_raw_data')
    op.drop_table('market_raw_data')
    op.drop_index('ix_market_indicators_date_weighted_priority', table_name='market_indicators')
    op.drop_index('ix_market_indicators_date_type', table_name='market_indicators')
    op.drop_index('ix_market_indicators_date_defense_status', table_name='market_indicators')
    op.drop_table('market_indicators')
    op.drop_table('market_index')
    op.drop_index('ix_ma_events_ticker_date', table_name='ma_events')
    op.drop_table('ma_events')
    op.drop_table('archive_pattern_stats')
    # ### end Alembic commands ###
